#!/usr/bin/env bash

echo "* Starting deployment of $APP_USER"

GIT_DIR=$(pwd)
cd ..

export RAILS_ENV=`git branch | grep '*' | awk '{print $2}' `

source /usr/local/rvm/scripts/rvm

echo "rvm current"
rvm current

echo "* Deploying on $RAILS_ENV"

echo "* checkout head"
env -i git reset --hard

echo '* deploy gems'
bundle install --without=development --deployment

echo '* rake db:migrate'
rake db:migrate

echo 'rake resque:work QUEUE=*'
rake resque:work QUEUE=*

echo 'rake daemon:tweetstream:start'
rake daemon:tweetstream:start

echo '* redeploying'
./script/unicorn start
