#!/usr/bin/env bash

echo "* Starting deployment of $APP_USER"

GIT_DIR=$(pwd)
cd ..

export RAILS_ENV=`git branch | grep '*' | awk '{print $2}' `

source /usr/local/rvm/scripts/rvm

echo "rvm current"
rvm current

echo "* Deploying on $RAILS_ENV"

echo "* checkout head"
env -i git reset --hard

echo '* deploy gems'
bundle install --without=development --deployment

echo '* rake db:migrate'
bundle exec rake db:migrate

echo '* start twetstream count'
bundle exec rake daemon:tweetstream:start

echo '* restart resque workers'
bundle exec rake resque:restart_workers

echo '* restart resque scheduler'
bundle exec rake resque:restart_scheduler

echo '* restart thin'
bundle exec thin -p 5000 -s 3 -e staging restart
