searchify: &searchify
  searchify_api_url: http://:rT47ovaCmkY3X4@8sk9q.api.searchify.com

open_calais: &open_calais
  open_calais_api_key: du295ff4zrg3rd4bwdk86xhy
  
development:
  <<: *open_calais
  <<: *searchify
  searchify_indices:
    locations: 'locations_staging'
    test: 'test_index'

test:
  <<: *open_calais
  <<: *searchify

production:
  <<: *open_calais
  <<: *searchify
