mysql: &mysql
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
#  socket: /tmp/mysql.sock
  charset: utf8
  collation: utf8_bin


common: &common
  # Choose one of the following
  <<: *mysql
  #<<: *postgres


development:
  <<: *common
  database: dimensions_dev

#production:
  #<<: *common
  #database: diaspora_production

test:
  <<: *common
  database: "dimensions_test<%= ENV['TEST_ENV_NUMBER'] %>"
