common: &common
  # Choose one of the following
  adapter: postgresql
  username: dev
  password: dev
  charset: utf8
  collation: utf8_bin


derelopment:
  <<: *common
  database: dimensions_dev

#production:
  #<<: *common
  #database: diaspora_production

test:
  <<: *common
  database: "dimensions_test<%= ENV['TEST_ENV_NUMBER'] %>"
