#CalculateRanking:
  #cron: "* * * * *"
  #class: RankingCalculator
  #args: *
  #description: "This function calculates the ranking of each feed entry"

CountFacebookLikes:
  cron: "*/5 * * * *"
  class: FacebookCounter
  description: "Updates the facebook likes count"
