CountFacebookLikes:
  cron: "0 */1 * * *"
  class: FacebookCounter
  description: "Updates the facebook likes count"

UpdateFeeds:
  cron: "00 */3 * * *"
  class: FeedUpdater
  description: "Update the feeds from the sources"

#ReindexFeeds:
  #cron: "00 */1 * * *"
  #class: EntryMonitor
  #description: "Retry to index the failed entries"

CleanSearchify:
  cron: "59 23 * * *"
  class: CleanIndexes
  description: "Clean indexes of old news"
