CountFacebookLikes:
  cron: "*/5 * * * *"
  class: FacebookCounter
  description: "Updates the facebook likes count"

UpdateFeeds:
  cron: "*/3 * * * *"
  class: FeedUpdater
  description: "Update the feeds from the sources"
